import "./globals.css";
import styles from "./layout.module.css";
import { Inter } from "next/font/google";
import Nav from "@/components/nav/Nav";
import type { NavItem } from "@/components/nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const items: Array<NavItem> = [
  { href: "/about", text: "About" },
  { href: "/about", text: "Experience" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Nav items={items} />
        </header>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
