import "./globals.css";
import cx from "classnames";
import { Exo_2 } from "next/font/google";
import styles from "./layout.module.css";
import Header from "@/components/header/Header";

const exo2 = Exo_2({ subsets: ["latin"], variable: "--font-exo2" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const setInitialTheme = `
    function getUserPreference() {
      if(window.localStorage.getItem('theme')) {
        return window.localStorage.getItem('theme')
      }
      return window.matchMedia('(prefers-color-scheme: dark)').matches
                ? 'dark'
                : 'light'
    }
    document.body.dataset.theme = getUserPreference();
  `;

  return (
    <html lang="en">
      <body className={exo2.className}>
        <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />
        <header className={cx(styles.main)}>
          <Header></Header>
        </header>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
